version: '2'
services:
  mysql:
    build: .
    image: bn0jdcook/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: new_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
